spring.application.name=BookhiveBackend

# Server
server.port=8082

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/bookhive
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging (optional but helpful while developing)
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.security=debug

google.books.api.key=AIzaSyDYyptZ-fHz1ZL7reWU691ptqz-F5dRa8A

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000